"""empty message

Revision ID: 81f2a88ea8f7
Revises: 369f068d1c41
Create Date: 2024-06-17 15:30:29.512069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f2a88ea8f7'
down_revision = '369f068d1c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
