"""empty message

Revision ID: 9afb7dad6f92
Revises: 0afa754e1c5f
Create Date: 2024-06-11 10:37:52.454411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afb7dad6f92'
down_revision = '0afa754e1c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_info_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pet_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('questionnaire_personal_info_fkey', type_='foreignkey')
        batch_op.drop_constraint('questionnaire_pet_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personal_info', ['personal_info_id'], ['id'])
        batch_op.create_foreign_key(None, 'pet', ['pet_id'], ['id'])
        batch_op.drop_column('personal_info')
        batch_op.drop_column('pet')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_info_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_personal_info_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personal_info', ['personal_info_id'], ['id'])
        batch_op.drop_column('personal_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_info', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_personal_info_fkey', 'personal_info', ['personal_info'], ['id'])
        batch_op.drop_column('personal_info_id')

    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('personal_info', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questionnaire_pet_fkey', 'pet', ['pet'], ['id'])
        batch_op.create_foreign_key('questionnaire_personal_info_fkey', 'personal_info', ['personal_info'], ['id'])
        batch_op.drop_column('pet_id')
        batch_op.drop_column('personal_info_id')

    # ### end Alembic commands ###
