"""empty message

Revision ID: d30ddce7b726
Revises: 9afb7dad6f92
Create Date: 2024-06-11 11:03:29.465056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30ddce7b726'
down_revision = '9afb7dad6f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('personal_info_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('personal_info_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
